### ISSUE TITLE
Nice screenshots!

### ISSUE THREAD

**Issue by PySimpleGUI** [ankitkumar-13/PyramidBuilder#1]
I'm really glad to see you added screenshots to your readme!  Happy partly because I get to see what you made.  It's really fun to get to see the many things people are making.  The other reason though is that other people get to see them too.  So many Python programs lack a GUI, so when one has a GUI, it's a real treat to see it.  It's not clear without screenshots that the program has a GUI.  I'm sure others stop and notice when they see the pictures.  Nice work!

**Comment by ankitkumar-13** [comment]
> I'm really glad to see you added screenshots to your readme!  Happy partly because I get to see what you made.  It's really fun to get to see the many things people are making.  The other reason though is that other people get to see them too.  So many Python programs lack a GUI, so when one has a GUI, it's a real treat to see it.  It's not clear without screenshots that the program has a GUI.  I'm sure others stop and notice when they see the pictures.  Nice work!
> 

Thanks for Appreciating...
